const modules = [
  {id:'passwords', icon:'🔐', title:'Contraseñas', subtitle:'Protegé el acceso a tus cuentas', learn:{title:'Una contraseña cuida la primera puerta', intro:'Las contraseñas son personales y no se comparten. Una clave extensa y única reduce el riesgo de accesos no autorizados.', points:[['Creá frases largas','Combiná palabras no relacionadas, números y símbolos. Como referencia corporativa, apuntá a 16 caracteres o más.'],['Evitá lo predecible','No uses 123456, fechas de nacimiento, nombres ni secuencias como abcd.'],['Mantenela privada','No la envíes por correo, chat ni se la prestes a colegas. Usá un gestor aprobado si está disponible.'],['Sumá una capa','La verificación en dos pasos protege incluso si alguien consigue tu contraseña.']]}, scenario:{title:'Un acceso “urgente”', person:'Pablo · compañero de oficina', image:'assets/characters/pablo.png', text:'Pablo, tu compañero de oficina, te escribe por chat: “Estoy bloqueado y necesito cerrar una operación. ¿Me pasás tu contraseña por cinco minutos?”', options:['Se la envío: es un compañero y la necesita con urgencia.','Le indico que use el proceso oficial de recuperación o contacte a soporte.','Le presto mi equipo con la sesión abierta.'], answer:1, feedback:'Las credenciales son personales e intransferibles. La urgencia nunca justifica compartirlas; el acceso debe recuperarse por los canales autorizados.'}, quiz:[['¿Cuál es la práctica más segura?', ['Reutilizar una contraseña conocida.','Usar una frase de contraseña larga y única.','Cambiar una letra por un número en mi fecha de nacimiento.'],1,'Una frase larga, única y difícil de predecir protege mejor la cuenta.'],['¿Qué acción compromete una contraseña robusta?', ['Guardarla en un gestor seguro aprobado.','Compartirla por correo no cifrado.','Activar la verificación en dos pasos.'],1,'Una clave fuerte deja de ser segura cuando se comparte por medios inseguros.'],['¿Para qué sirve la verificación en dos pasos?', ['Para sumar una capa de protección además de la contraseña.','Para que la aplicación sea más rápida.','Para evitar actualizar la clave.'],0,'El segundo factor dificulta el acceso aunque una contraseña sea comprometida.']]},
  {id:'data', icon:'🛡️', title:'Protección de datos', subtitle:'Cuidá tu información y la de otras personas', learn:{title:'Los datos requieren decisiones seguras', intro:'La información personal, financiera y de tarjetas puede usarse para fraudes o robos. Cuidarla es importante tanto en la vida diaria como en el trabajo.', points:[['Reconocé información sensible','Documentos, tarjetas, credenciales, fotos privadas y datos de contacto no se comparten sin necesidad.'],['Elegí canales seguros','No envíes información sensible por correos o chats personales si existe un canal seguro para hacerlo.'],['Conectate con cuidado','Evitá operaciones sensibles desde Wi-Fi público. Preferí redes conocidas y protegidas.'],['Actualizá tus herramientas','Las actualizaciones corrigen problemas de seguridad y mantienen protegidos tus dispositivos.']]}, scenario:{title:'La planilla desde el café', person:'Carla · compañera de equipo', image:'assets/characters/carla.png', text:'Carla te escribe: “Estoy en un café con Wi-Fi gratis. ¿Me mandás por acá la planilla con datos de contacto para adelantar trabajo?”', options:['La envío por el chat para no retrasar la tarea.','Le propongo esperar una conexión confiable y usar el canal acordado.','Le saco el título al archivo y se la mando por mensajería.'], answer:1, feedback:'Los datos sensibles no deberían viajar por redes o canales no verificados. Una demora breve es preferible a exponer información.'}, quiz:[['¿Por qué proteger los datos compartidos en internet?', ['Pueden usarse para fraudes o robos.','Hace que las páginas carguen más rápido.','Evita gastar batería.'],0,'Los datos personales pueden ser explotados por personas malintencionadas.'],['¿Qué se recomienda al usar Wi-Fi pública?', ['Ingresar a cuentas sensibles si la red tiene un nombre conocido.','Evitar compras, pagos y operaciones sensibles.','Enviar información sensible solo si es urgente.'],1,'Las redes públicas pueden exponer la información transmitida.'],['¿Qué medida suma protección a una cuenta?', ['Activar la verificación en dos pasos.','Compartir la clave solo con conocidos.','Desactivar actualizaciones.'],0,'La verificación en dos pasos agrega una capa adicional de seguridad.']]},
  {id:'grooming', icon:'👤', title:'Grooming', subtitle:'Detectá y reportá contactos riesgosos', learn:{title:'Las señales importan', intro:'El grooming es una forma de manipulación en línea en la que un adulto busca ganarse la confianza de menores para obtener información, imágenes o encuentros.', points:[['Desconfiá de secretos y presiones','Pedidos de mantener conversaciones ocultas, fotos o datos personales son señales de alerta.'],['Cuidá la información','No compartas ubicación, rutinas, escuela ni imágenes con desconocidos.'],['No enfrentes ni borres evidencia','Conservá capturas y conversaciones relevantes para poder reportar.'],['Acompañá y reportá','Escuchá sin culpar. Bloqueá la cuenta y buscá ayuda en los canales correspondientes.']]}, scenario:{title:'Consulta de una clienta', person:'Sofía · clienta', image:'assets/characters/sofia.png', text:'Sofía comenta que su hijo recibe mensajes de alguien que dice tener su edad, pide fotos y le solicita que no se lo cuente a nadie.', options:['Le recomiendo que el menor continúe hablando para conocer sus intenciones.','Le sugiero guardar evidencia, bloquear el contacto y buscar ayuda de un adulto y canales de denuncia.','Le indico borrar todo para que nadie vea los mensajes.'], answer:1, feedback:'Los secretos, pedidos de imágenes y presión son alertas. Conservar evidencia, bloquear y buscar ayuda protege a la persona afectada.'}, quiz:[['¿Cuál es una señal de alerta?', ['Un contacto pide mantener la conversación en secreto.','Un familiar envía un saludo.','Una aplicación solicita actualizarse.'],0,'Las peticiones de secreto y aislamiento son tácticas frecuentes de manipulación.'],['¿Qué conviene hacer ante un posible caso?', ['Guardar evidencia y pedir ayuda.','Responder con amenazas.','Publicar la conversación en redes.'],0,'Es importante acompañar, conservar evidencia y usar canales seguros de ayuda.'],['¿Qué dato no debe compartirse con desconocidos?', ['La ubicación y rutina.','El color favorito.','Una recomendación de música.'],0,'Ubicación, rutinas e imágenes pueden poner en riesgo la seguridad personal.']]},
  {id:'email', icon:'✉️', title:'Correo personal / corporativo', subtitle:'Usá cada cuenta y canal con cuidado', learn:{title:'Un correo puede abrir una puerta o una trampa', intro:'El correo sirve para conversar, comprar, estudiar y trabajar. Por eso conviene separar las cuentas y mirar cada mensaje con atención antes de actuar.', points:[['Separá lo personal de lo laboral','No reenvíes documentos de trabajo o datos de otras personas a tu correo personal.'],['Verificá antes de actuar','Revisá remitente, dominio, enlaces y adjuntos antes de abrirlos.'],['Informá lo sospechoso','Los mensajes falsos suelen generar urgencia o pedir claves. Pedí ayuda o reportalos.'],['Usá recursos autorizados','Para información de trabajo, compartí archivos solo mediante plataformas y destinatarios aprobados.']]}, scenario:{title:'“¿Me lo reenviás a mi cuenta personal?”', person:'Martín · compañero de equipo', image:'assets/characters/martin.png', text:'Martín te escribe: “No puedo entrar al correo del trabajo. Reenviame el archivo del proyecto a mi cuenta personal, así avanzo desde casa.”', options:['Se lo reenvío porque conozco a Martín.','Le propongo esperar el acceso o usar el proceso y canal acordados.','Le mando capturas por una red social para que no ocupe tanto espacio.'], answer:1, feedback:'Aunque conozcas a la persona, los archivos de trabajo deben circular por los canales definidos. Eso protege la información y permite saber quién accedió.'}, quiz:[['¿Cuándo usar el correo personal?', ['Para reenviar un archivo laboral urgente.','Para guardar una copia de respaldo de un informe.','Para asuntos personales, no para información o gestiones de la empresa.'],2,'El correo personal no tiene los mismos controles que una cuenta de trabajo.'],['¿Qué puede indicar phishing?', ['Un mensaje que genera urgencia y pide credenciales.','Un boletín interno que estabas esperando.','Un correo que ya verificaste con su remitente por otro canal.'],0,'La urgencia y el pedido de datos son señales que requieren verificación.'],['¿Qué hacer con un enlace sospechoso?', ['Abrirlo en una ventana privada.','No interactuar y pedir ayuda o reportarlo.','Reenviarlo a todo el equipo.'],1,'No interactúes con enlaces sospechosos; reportarlos permite una respuesta segura.']]},
  {id:'threats', icon:'⚠️', title:'Amenazas cibernéticas', subtitle:'Reconocé ataques antes de que causen daño', learn:{title:'Reconocer una amenaza permite frenarla', intro:'No todos los ataques se ven igual. Conocer sus señales ayuda a actuar antes de que un mensaje, archivo o enlace afecte a la organización.', points:[['Malware','Es un software diseñado para dañar, alterar o acceder a un equipo sin autorización.'],['Ransomware','Es un tipo de malware que cifra o bloquea archivos y puede exigir un pago.'],['Phishing, smishing y vishing','Buscan engañar por correo, mensaje o llamada para obtener datos o lograr una acción apresurada.'],['Detené y reportá','No abras adjuntos ni enlaces dudosos. Verificá por un canal oficial y avisá al área responsable.']]}, scenario:{title:'El correo que bloquea la cuenta', visual:'✉️', text:'Joaquín recibe un correo que dice: “Tu cuenta será bloqueada hoy. Verificá tus datos ahora” e incluye un enlace.', options:['Abro el enlace rápido para evitar el bloqueo.','Reconozco un posible phishing, no interactúo y lo reporto.','Reenvío el correo a mis compañeros para que también revisen su cuenta.'], answer:1, feedback:'Un correo urgente que pide datos mediante un enlace es una señal típica de phishing. No interactúes y reportalo.'}, quiz:[['¿Qué describe mejor al ransomware?', ['Un programa que cifra o bloquea información.','Una actualización del sistema.','Un método para mejorar el Wi-Fi.'],0,'El ransomware busca impedir el acceso a los datos y puede exigir un rescate.'],['¿Qué tipo de engaño llega por llamada telefónica?', ['Vishing.','Smishing.','Spyware.'],0,'El vishing usa llamadas para presionar o suplantar identidades.'],['¿Qué hacer ante un adjunto inesperado?', ['Abrirlo en modo privado.','Verificar y reportar antes de abrirlo.','Reenviarlo a todo el equipo.'],1,'Detenerse, verificar y reportar limita el impacto de una posible amenaza.']]},
  {id:'social', icon:'🧑‍💻', title:'Ingeniería social', subtitle:'Protegé tu puesto y verificá identidades', learn:{title:'El atacante puede buscar manipular a una persona', intro:'La ingeniería social usa urgencia, confianza o autoridad aparente para lograr que alguien entregue datos, abra un acceso o realice una acción insegura.', points:[['Verificá la identidad','Que alguien conozca tu nombre o rol no prueba que sea quien dice ser. Usá un canal oficial.'],['No compartas secretos','Contraseñas, códigos MFA y datos internos nunca se solicitan por llamada o chat informal.'],['Cuidá el puesto de trabajo','Bloqueá la pantalla al alejarte y resguardá documentos confidenciales.'],['Desconfiá de objetos desconocidos','Un USB encontrado o un visitante que intenta ingresar sin autorización debe reportarse.']]}, scenario:{title:'“Soy de Sistemas, necesito tu código”', visual:'☎️', text:'Una persona llama a Sofía, dice ser de Sistemas y le pide usuario, contraseña y un código MFA para una actualización urgente.', options:['Le doy el código porque conoce mi nombre y sector.','No comparto datos y verifico el pedido con Sistemas por un canal oficial.','Le doy solo el código MFA para que la actualización sea rápida.'], answer:1, feedback:'La urgencia y la supuesta autoridad son recursos de manipulación. Verificá por un canal oficial y no compartas credenciales.'}, quiz:[['¿Qué es tailgating?', ['Ingresar a un sector siguiendo a una persona autorizada.','Actualizar un antivirus.','Cambiar una contraseña.'],0,'No permitas que una persona ingrese a un área restringida sin validar su acceso.'],['¿Qué corresponde al alejarse del puesto?', ['Bloquear la pantalla.','Dejar la sesión abierta por si volvés pronto.','Compartir el equipo con cualquiera.'],0,'Bloquear la pantalla protege información y accesos cuando no estás presente.'],['¿Qué hacer con un USB desconocido?', ['Conectarlo para ver qué contiene.','Reportarlo y no conectarlo.','Llevarlo a casa.'],1,'Un USB puede contener software malicioso; reportarlo evita exponer equipos y datos.']]}
];
const orderedModules=['passwords','email','data','threats','social','grooming'].map(id=>modules.find(module=>module.id===id));
modules.find(module=>module.id==='threats').quiz[0]=[
  'Al abrir sus documentos, un usuario ve un mensaje que exige un pago y todos los archivos tienen una extensión desconocida. ¿Qué puede estar ocurriendo?',
  ['Una posible infección de ransomware que cifró los archivos para exigir un rescate.','Una actualización de seguridad que cambió temporalmente el formato de los archivos.','Una falla de sincronización que se resuelve enviando los documentos por correo.'],
  0,
  'El ransomware puede cifrar o bloquear información y exigir un pago. Ante una sospecha, no continúes operando y reportá el incidente.'
];
const extraActivities={
passwords:{scenario:{title:'La nota junto a la compu',person:'Pablo · compañero',image:'assets/characters/pablo.png',text:'Pablo dejó una nota con su contraseña junto al monitor porque así puede recordarla con facilidad.',options:['Le sugiero retirarla y usar una frase de contraseña o un gestor seguro.','Le propongo guardar la nota dentro de un cajón con llave.','Le sugiero cambiar la clave cada semana y conservarla anotada.'],answer:0,feedback:'Las contraseñas no deben quedar a la vista. Una frase segura o un gestor de contraseñas evita exponerlas.'},quiz:[['¿Qué dato conviene evitar en una contraseña?', ['Una fecha de nacimiento combinada con algo fácil de relacionar con vos.','Palabras aleatorias y no relacionadas.','Símbolos combinados con una frase extensa.'],0,'La información personal suele ser fácil de descubrir, incluso si se combina con otros datos.'],['¿Qué práctica reduce mejor el impacto de una filtración?', ['Usar una clave única por cuenta.','Reutilizar una clave robusta en sitios de confianza.','Cambiar la misma clave cada tres meses en todos los servicios.'],0,'Las claves únicas reducen el impacto de una filtración.']]},
data:{scenario:{title:'Una foto para terminar después',visual:'📄',text:'Terminás una tarea y pensás sacarle una foto a una lista con nombres y teléfonos para seguirla desde tu celular personal.',options:['Uso solo las herramientas y canales acordados para guardar o compartir la lista.','La guardo en mi galería: mi teléfono tiene bloqueo.','La envío a mi correo personal y la borro al terminar.'],answer:0,feedback:'Los datos de otras personas deben guardarse y compartirse mediante las herramientas acordadas, no en cuentas o dispositivos personales.'},quiz:[['¿Cuál de estos elementos requiere mayor protección?', ['Un correo de cumpleaños con fotos grupales de compañeros.','Una planilla con nombres, DNI y números de tarjeta.','La invitación a una reunión general.'],1,'Los datos financieros y personales identificables son información sensible y requieren más cuidado.'],['¿Qué ayuda a proteger un dispositivo?', ['Mantenerlo actualizado mediante las herramientas disponibles.','Posponer actualizaciones hasta que el equipo funcione más lento.','Actualizar solo aplicaciones de entretenimiento.'],0,'Las actualizaciones corrigen problemas de seguridad conocidos.']]},
grooming:{scenario:{title:'Un pedido de ayuda',person:'Sofía · madre preocupada',image:'assets/characters/sofia.png',text:'Sofía duda si debe borrar los mensajes sospechosos que recibió su hijo antes de hablar con un adulto.',options:['Le sugiero conservar capturas, bloquear el contacto y pedir ayuda.','Le sugiero borrar el chat tras guardar el nombre de usuario en una nota.','Le propongo responder una sola vez para confirmar que la cuenta no es real.'],answer:0,feedback:'Las capturas ayudan a pedir ayuda y reportar el caso. No conviene responder ni borrar evidencia.'},quiz:[['¿Qué combinación es una señal de alerta más relevante?', ['Un contacto insiste en secretos, fotos y pasar a otro chat privado.','Un compañero de escuela comparte una publicación pública.','Una aplicación avisa que hay una actualización disponible.'],0,'El aislamiento y los secretos son señales de manipulación.'],['¿Qué corresponde ante una señal de riesgo?', ['Bloquear, conservar evidencia y pedir ayuda a un adulto responsable.','Restringir el perfil y continuar la conversación para obtener más datos.','Publicar el chat en redes para pedir opiniones.'],0,'Bloquear el contacto y buscar apoyo es una respuesta segura.']]},
email:{scenario:{title:'Un adjunto inesperado',person:'Martín · compañero de equipo',image:'assets/characters/martin.png',text:'Martín te reenvía un correo inesperado con un archivo adjunto y te pide abrirlo “urgente” para validar datos.',options:['Verifico el mensaje por un canal conocido y pido ayuda si parece sospechoso.','Abro el archivo en una ventana privada para limitar el riesgo.','Le respondo el mismo correo solicitando que confirme que fue él.'],answer:0,feedback:'La urgencia es una señal común de phishing. Verificá por otro canal antes de abrir enlaces o adjuntos.'},quiz:[['¿Qué conviene revisar en un correo inesperado?', ['El remitente completo, el dominio y el destino real del enlace.','Solo si el saludo incluye tu nombre completo.','Que el logo de la empresa se vea nítido.'],0,'Verificar remitente y destino de enlaces ayuda a detectar fraudes.'],['¿Dónde se comparten archivos de trabajo con datos sensibles?', ['En plataformas autorizadas y con los permisos correspondientes.','En correo personal si el archivo tiene contraseña.','Por un enlace temporal en una red social privada.'],0,'Las plataformas autorizadas mantienen los controles y permiten saber quién accedió.']]},
threats:{scenario:{title:'El archivo “recibo”',visual:'🦠',text:'Te llega un archivo ejecutable llamado Recibo_urgente.exe desde un remitente que no reconocés.',options:['No lo abro, verifico el origen por un canal conocido y lo reporto.','Lo guardo sin abrir para revisarlo cuando termine mi jornada.','Le cambio la extensión antes de abrirlo para que sea más seguro.'],answer:0,feedback:'Un archivo ejecutable inesperado puede contener malware. No lo abras y reportalo.'},quiz:[['¿Por qué no se debe pagar un rescate ante ransomware?', ['No garantiza recuperar la información y puede financiar nuevos ataques.','Porque el pago suele demorar demasiado tiempo.','Porque elimina automáticamente las copias de seguridad.'],0,'La prevención, los respaldos y el reporte son la respuesta adecuada frente al ransomware.'],['¿Qué medio usa el smishing?', ['Mensajes de texto o mensajería.','Llamadas telefónicas.','Memorias USB encontradas.'],0,'El smishing es phishing que llega mediante mensajería de texto o aplicaciones de mensajería.']]},
social:{scenario:{title:'El USB encontrado',visual:'💾',text:'Nicolás encuentra un USB sin identificar en la recepción y piensa conectarlo para saber de quién es.',options:['Lo reporta y no lo conecta.','Lo conecta en un equipo que no tiene archivos importantes.','Le pregunta a varias personas y, si nadie lo reconoce, revisa su contenido.'],answer:0,feedback:'Los USB desconocidos pueden contener malware. Deben reportarse sin conectarlos.'},quiz:[['¿Qué dato jamás se comparte por una llamada no verificada?', ['Contraseña o código MFA.','El horario de atención general.','El nombre del sector en el que trabajás.'],0,'Las credenciales y códigos son secretos; Sistemas no los pide por teléfono.'],['¿Qué ayuda a evitar shoulder surfing?', ['Proteger la pantalla y bloquearla al alejarse.','Reducir el brillo de la pantalla cuando hay visitas.','Ubicar los documentos boca abajo, pero mantener la sesión abierta.'],0,'Resguardar la pantalla y los documentos evita que terceros observen información sensible.']]}
};

const learnDetails={
passwords:[
'Una contraseña no es un simple requisito de acceso: es una prueba de identidad. Si otra persona la conoce, puede actuar con tu cuenta, consultar información, enviar mensajes o realizar acciones que luego quedarán asociadas a tu usuario. Por eso, una contraseña segura reduce el riesgo, pero no reemplaza las políticas, los controles ni la atención de quien la utiliza.',
'La longitud es especialmente importante porque aumenta la cantidad de combinaciones posibles. Una frase de contraseña con palabras no relacionadas resulta más fácil de recordar y más difícil de adivinar que un nombre, una fecha o una secuencia. Cada cuenta importante debe tener una clave distinta: si un servicio externo sufre una filtración, una clave reutilizada puede abrir la puerta a otros sistemas.',
'El segundo factor de autenticación agrega una barrera adicional. Sin embargo, un código MFA también es secreto: nunca debe aprobarse una solicitud inesperada ni compartirse con otra persona. Un gestor de contraseñas aprobado ayuda a usar claves únicas sin anotarlas en papeles, chats o archivos expuestos.'
],
data:[
'La información no está solo en una base de datos: también aparece en planillas, correos, fotos, conversaciones, documentos, celulares y archivos compartidos. Protegerla es cuidar que llegue solo a quien corresponde y que no se pierda ni se modifique por error.',
'Antes de compartir un dato, hacete tres preguntas simples: ¿es necesario?, ¿la persona correcta lo necesita? y ¿estoy usando el medio adecuado? Los datos personales, financieros, las claves y los documentos privados merecen especial cuidado. Que algo sea urgente no responde esas preguntas por vos.',
'La protección también depende de hábitos cotidianos: bloquear la pantalla, actualizar los dispositivos y no usar nubes o correos personales para guardar información de otras personas. Una pérdida de datos puede afectar a alguien, generar engaños o perjudicar una organización.',
'En una Wi-Fi pública o desconocida alguien podría intentar mirar o redirigir lo que enviás. Para pagos, contraseñas, trámites o trabajo con datos, esperá una red confiable. Si una conexión no te da confianza, lo más seguro es no transmitir información.'
],
grooming:[
'El grooming es una forma de manipulación digital. Una persona adulta puede buscar ganarse la confianza de un menor mediante perfiles falsos, halagos, regalos, secretos o conversaciones aparentemente inocentes. El objetivo puede ser obtener imágenes, información personal, aislar a la víctima o intentar un encuentro.',
'Las señales de alerta suelen aparecer de forma gradual: pedidos de mantener el contacto en secreto, presión para responder, preguntas sobre ubicación o rutinas, solicitudes de fotos y cambios repentinos a canales privados. No es responsabilidad de la persona afectada; el acompañamiento sin culpas es esencial para que pueda pedir ayuda.',
'Frente a una situación de riesgo, no se recomienda confrontar al posible agresor ni borrar la conversación. Conservar capturas, bloquear el contacto y recurrir a un adulto responsable y a los canales de ayuda permite cuidar a la persona y preservar evidencia para una denuncia si corresponde.'
],
email:[
'Una cuenta de correo personal es para tu vida privada; una cuenta de trabajo puede tener reglas y protecciones propias. Separarlas evita que los archivos o datos de una organización queden en lugares que no puede cuidar ni controlar.',
'Muchos engaños comienzan con un mensaje aparentemente normal. Pueden copiar el logo de una marca, usar un nombre conocido, generar urgencia o pedir claves y pagos. Antes de hacer clic, revisá quién escribe, el dominio, el enlace y si el pedido tiene sentido. Un mensaje esperado también puede ser falso.',
'No abras adjuntos inesperados ni archivos que te pidan habilitar algo para funcionar. Si tenés dudas, preguntale a la persona por otro canal conocido o pedí ayuda. Avisar a tiempo puede evitar que otras personas reciban el mismo engaño.',
'La seguridad no depende de memorizar reglas difíciles: usá la cuenta correcta, verificá antes de enviar, compartí solo con quien corresponde y frená cuando algo te apura o te resulta extraño.'
],
threats:[
'Una amenaza digital puede llegar por un correo, un mensaje, una llamada, un archivo, un código QR o una red Wi-Fi falsa. No hace falta saber informática para reconocer muchas señales: urgencia, pedidos de claves, enlaces extraños o algo que no esperabas.',
'Malware es el nombre general de programas creados para dañar o espiar. Ransomware es un tipo que puede bloquear archivos y pedir dinero. Phishing, smishing y vishing son engaños por correo, mensajería o llamadas que intentan apurarte para que entregues datos o hagas clic.',
'No tenés que resolver un incidente por tu cuenta. Si sospechás algo, dejá de interactuar: no hagas clic, no ingreses más datos y no reenvíes el mensaje. Pedí ayuda o reportalo por el canal disponible; hacerlo rápido ayuda a frenar el problema.',
'A veces la seguridad detecta señales raras, como muchos intentos de acceso o una cuenta usada desde un lugar inusual. Estas alertas se revisan para confirmar qué pasó. Tu aviso también puede ser la primera señal que permita proteger una cuenta o un equipo.'
],
social:[
'La ingeniería social no necesita vulnerar una computadora primero: busca influir en una persona. Un atacante puede presentarse como técnico, proveedor, cliente o directivo; usar un problema urgente; o aprovechar información pública para parecer confiable. La presión busca que se actúe antes de pensar y verificar.',
'Ninguna persona debería compartir contraseñas, códigos de autenticación, accesos remotos ni documentación sensible por una llamada, chat o correo no verificado. La forma segura de validar una solicitud es cortar la conversación o no responder y comunicarse mediante el número, correo o canal oficial de la organización.',
'La seguridad del puesto de trabajo es parte de esta defensa: bloquear la pantalla al alejarse, guardar documentos, no permitir accesos físicos sin validar y reportar USB u objetos desconocidos. Las medidas técnicas son más fuertes cuando las personas también reconocen intentos de manipulación.',
'Los controles físicos y administrativos también protegen la red: credenciales de acceso, sectores restringidos, cámaras, inventario de equipos y permisos por perfil reducen oportunidades de abuso. Cada persona debe acceder solo a la información y los recursos necesarios para su función, y cualquier excepción debe seguir el procedimiento autorizado.'
]};
const learnFollowUps={
passwords:[{prompt:'Si una web externa sufre una filtración, ¿qué evita que afecte a tus otras cuentas?',options:['Usar una contraseña única por cuenta','Usar el mismo patrón en todas','Cambiar solo un número'],answer:0,feedback:'Las claves únicas limitan el impacto de una filtración.'},{prompt:'¿Qué hacés ante una aprobación MFA que no solicitaste?',options:['La aprobás por si acaso','No la aprobás y verificás o reportás','Compartís el código con soporte'],answer:1,feedback:'Una solicitud inesperada puede indicar que alguien intenta ingresar a tu cuenta.'}],
data:[{prompt:'¿Qué criterio guía el envío de información sensible?',options:['Urgencia del pedido','Canal autorizado y destinatario validado','Que el archivo sea pequeño'],answer:1,feedback:'La necesidad de compartir datos nunca reemplaza la validación y el canal seguro.'},{prompt:'En una Wi-Fi pública, ¿qué decisión reduce el riesgo?',options:['Ingresar igual por ser rápido','Evitar operaciones sensibles y esperar una red confiable','Enviar los datos en varios mensajes'],answer:1,feedback:'Una red no verificada puede exponer o redirigir información.'}],
grooming:[{prompt:'¿Qué conducta es una señal de manipulación?',options:['Pedir secretos y aislar a la persona','Recomendar hablar con un adulto','Respetar límites'],answer:0,feedback:'Los secretos y la presión buscan impedir que la víctima pida ayuda.'},{prompt:'¿Qué conviene conservar ante un contacto riesgoso?',options:['Capturas y mensajes relevantes','Solo el nombre de usuario','Nada: borrar todo'],answer:0,feedback:'La evidencia puede ayudar a reportar el caso de forma segura.'}],
email:[{prompt:'¿Qué verificás en un correo inesperado?',options:['Remitente, dominio y enlace real','Solo el logo','La hora de recepción'],answer:0,feedback:'Los detalles del origen ayudan a detectar una suplantación.'},{prompt:'¿Qué hacés con un adjunto ejecutable inesperado?',options:['Lo abrís para revisarlo','No lo abrís y lo reportás','Lo reenviás a un compañero'],answer:1,feedback:'Los archivos inesperados pueden contener malware.'}],
threats:[{prompt:'¿Qué práctica ayuda a limitar el impacto de ransomware?',options:['Copias de seguridad y actualizaciones','Desactivar el antivirus','Usar contraseñas de fábrica'],answer:0,feedback:'Los respaldos probados y los parches son capas clave de resiliencia.'},{prompt:'El monitoreo detecta que una cuenta accedió de madrugada desde una ubicación inusual. Antes de asumir que es un ataque, ¿qué corresponde?',options:['Validar el evento según el procedimiento y escalarlo si la anomalía se confirma.','Cerrar la alerta porque la persona podría estar trabajando desde su casa.','Restablecer la contraseña de todas las cuentas sin investigar el caso.'],answer:0,feedback:'Una alerta no confirma por sí sola un incidente, pero debe analizarse y escalarse siguiendo el procedimiento para contener un riesgo real a tiempo.'}],
social:[{prompt:'¿Cómo validás a quien pide información por teléfono?',options:['Por su tono de urgencia','Usando un canal oficial independiente','Porque conoce tu nombre'],answer:1,feedback:'La identidad debe verificarse fuera de la comunicación sospechosa.'},{prompt:'¿Qué protege el puesto al alejarte?',options:['Bloquear pantalla y resguardar documentos','Dejar la sesión abierta','Compartir el equipo'],answer:0,feedback:'El control físico es una capa de seguridad diaria.'}]};
function miniChallengeFor(m,phase){return phase===0?learnChallenges[m.id]:learnFollowUps[m.id][phase-1]}
const app = document.querySelector('#app');
const state = {score:0, completed:new Set(), moduleSteps:{}, moduleScores:{}, hangman:null,user:null};
const passScores={passwords:120,data:120,grooming:120,email:120,threats:120,social:120};
const learnChallenges={passwords:{prompt:'María usaba Maria123. ¿Cuál es una contraseña más segura?',options:['Maria2026!','M4ria123!','Río!Luna_84#Tren'],answer:2,feedback:'Una frase larga, única y sin datos personales es mucho más difícil de adivinar.'},data:{prompt:'¿Cuál de estos elementos requiere mayor protección?',options:['Una noticia pública','El número de una tarjeta','El pronóstico del clima'],answer:1,feedback:'Los datos financieros y personales son sensibles y solo deben tratarse por canales autorizados.'},grooming:{prompt:'¿Qué señal requiere atención inmediata?',options:['Un pedido de mantener secretos y enviar fotos','Una actualización de una aplicación','Un saludo de un familiar'],answer:0,feedback:'Los secretos, la presión y los pedidos de imágenes son señales de alerta.'},email:{prompt:'¿Qué revisás antes de abrir un enlace?',options:['El remitente, dominio y destino del enlace','Solo el asunto','El color del correo'],answer:0,feedback:'Revisar el origen y el destino real ayuda a detectar mensajes fraudulentos.'},threats:{prompt:'Un correo urgente con enlace para “evitar un bloqueo” puede ser…',options:['Phishing','Backup','Firewall'],answer:0,feedback:'El phishing utiliza correos engañosos para generar urgencia y robar información.'},social:{prompt:'¿Qué hacés ante una llamada “urgente” que pide tu código MFA?',options:['Lo comparto para no demorar','Corto y verifico con el área por un canal oficial','Doy solo el código'],answer:1,feedback:'La verificación por un canal oficial evita caer en una suplantación.'}};
const finalQuestions=[{module:'passwords',q:'Un compañero pide tu contraseña por una urgencia. ¿Qué hacés?',o:['La comparto por cinco minutos','Indico el proceso oficial de recuperación','Le presto mi sesión abierta'],a:1},{module:'data',q:'¿Dónde compartís una planilla con datos sensibles?',o:['En una nube personal','Por mensajería','Solo en una plataforma de trabajo autorizada'],a:2},{module:'grooming',q:'Ante pedidos de secretos, fotos y aislamiento, ¿qué corresponde?',o:['Guardar evidencia y pedir ayuda','Continuar para conocer la intención','Borrar todo de inmediato'],a:0},{module:'email',q:'Un correo urgente pide tus credenciales. ¿Qué hacés?',o:['Pido ayuda o lo reporto sin interactuar','Respondo para verificar','Abro el enlace en incógnito'],a:0},{module:'threats',q:'Un mensaje por WhatsApp con un enlace falso para robar datos es…',o:['Vishing','Smishing','Ransomware'],a:1},{module:'social',q:'Al alejarte de tu escritorio, la acción segura es…',o:['Bloquear la pantalla','Dejar todo abierto','Compartir la sesión'],a:0},{module:'passwords',q:'Recibís una aprobación de segundo factor que no solicitaste. ¿Cuál es la mejor respuesta?',o:['Aprobarla si aparece varias veces para que deje de insistir','Rechazarla y verificar el intento por un canal conocido','Compartir el código con soporte para que revise el caso'],a:1},{module:'data',q:'Alguien te pide datos de una persona por un canal distinto al habitual. ¿Qué decisión protege mejor la información?',o:['Enviar solo una parte de los datos para responder rápido','Validar identidad, necesidad y canal adecuado antes de compartir','Reenviar el pedido a una cuenta personal para revisarlo después'],a:1},{module:'email',q:'Una persona conocida envía un archivo inesperado desde una dirección levemente distinta. ¿Qué hacés?',o:['Lo abrís porque el nombre coincide','Verificás el pedido por otro canal antes de abrirlo','Lo reenviás a alguien para que lo pruebe'],a:1},{module:'threats',q:'Un equipo muestra archivos con extensiones desconocidas y un aviso de pago. ¿Qué acción inicial es más adecuada?',o:['Seguir trabajando y reiniciar al finalizar el día','Dejar de usarlo y avisar según el procedimiento disponible','Pagar de inmediato para recuperar los archivos'],a:1}];
const signalChallenges=[
{title:'Mensaje que apura',text:'Te llega un WhatsApp que parece ser de una empresa conocida: “Tu paquete está retenido. Pagá ahora desde este enlace”.',answer:'Frenar y verificar por la web o app oficial, sin abrir el enlace.',signals:['Te apura a actuar','Tiene un enlace','Pide un pago inesperado']},
{title:'Aprobación inesperada',text:'Tu celular muestra una solicitud para aprobar el acceso a tu cuenta, pero vos no estabas iniciando sesión.',answer:'Rechazarla y cambiar o revisar la cuenta por un canal conocido.',signals:['No iniciaste sesión','Alguien podría tener tu clave','El código no se comparte']},
{title:'USB encontrado',text:'Encontrás un USB en la entrada de tu trabajo o edificio, con una etiqueta que dice “Fotos”.',answer:'No conectarlo; entregarlo o reportarlo para que se revise de forma segura.',signals:['El dueño es desconocido','Puede contener archivos peligrosos','La curiosidad no es un control de seguridad']}
];
const hangmanWords=[{word:'RANSOMWARE',definition:'Tipo de software malicioso que bloquea o cifra información y exige un pago para recuperarla.'},{word:'PHISHING',definition:'Engaño que busca obtener credenciales o datos mediante mensajes, sitios o enlaces falsos.'},{word:'MALWARE',definition:'Término general para programas diseñados para dañar, alterar o acceder sin autorización a un equipo.'}];
const $=s=>document.querySelector(s); const clone=id=>$('#'+id).content.cloneNode(true); const pointsPill=points=>`<span class="points-pill">${points} pts</span>`;
function readSavedUser(){try{return JSON.parse(localStorage.getItem('cq_demo_session')||sessionStorage.getItem('cq_demo_session')||'null')}catch{try{localStorage.removeItem('cq_demo_session');sessionStorage.removeItem('cq_demo_session')}catch{}return null}}
function shuffledOptions(options,key){let hash=0;for(const char of key)hash=(hash*31+char.charCodeAt(0))>>>0;const shift=hash%options.length;return options.map((text,index)=>({text,index,order:(index+shift)%options.length})).sort((a,b)=>a.order-b.order)}
function celebrate(){const layer=document.createElement('div');layer.className='celebration';['✦','★','🎉','✦','✨','🎊','★'].forEach((symbol,i)=>{const bit=document.createElement('span');bit.className='confetti';bit.textContent=symbol;bit.style.setProperty('--x',`${(i-3)*62}px`);bit.style.setProperty('--y',`${-80-(i%3)*55}px`);layer.append(bit)});document.body.append(layer);setTimeout(()=>layer.remove(),900)}
function playUnlockSound(){try{const Ctx=window.AudioContext||window.webkitAudioContext,ctx=new Ctx(),now=ctx.currentTime;[440,660,880].forEach((freq,index)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=freq;osc.type='sine';gain.gain.setValueAtTime(.0001,now+index*.12);gain.gain.exponentialRampToValueAtTime(.13,now+index*.12+.02);gain.gain.exponentialRampToValueAtTime(.0001,now+index*.12+.28);osc.connect(gain).connect(ctx.destination);osc.start(now+index*.12);osc.stop(now+index*.12+.3)});setTimeout(()=>ctx.close(),900)}catch{}}
function showUnlockCinematic(title){const layer=document.createElement('div');layer.className='unlock-cinematic';const stars=document.createElement('div');stars.className='unlock-stars';for(let i=0;i<28;i++){const star=document.createElement('span');star.className='unlock-star';star.textContent=i%4===0?'★':'✦';star.style.setProperty('--left',`${Math.random()*100}%`);star.style.setProperty('--delay',`${Math.random()*.65}s`);star.style.setProperty('--duration',`${1.05+Math.random()*.8}s`);star.style.setProperty('--size',`${10+Math.random()*18}px`);stars.append(star)}layer.append(stars);layer.insertAdjacentHTML('beforeend',`<div>✦ Misión superada<small>${title} se convierte en un logro de piedra</small></div>`);document.body.append(layer);setTimeout(()=>layer.remove(),2100)}
function updateHeader(){const pct=Math.round(state.completed.size/modules.length*100);$('#score').textContent=state.score;$('#globalProgress').style.width=pct+'%';$('#globalProgressText').textContent=pct+'%';$('#logoutBtn').classList.toggle('hidden',!state.user)}
function isUnlocked(i){return state.user?.role==='admin'||i===0||state.completed.has(orderedModules[i-1].id)}
function renderDashboard(){
  app.replaceChildren(clone('dashboardTemplate'));
  const greeting=$('#userGreeting');
  const firstName=String(state.user?.name||'').trim().split(/\s+/)[0];
  greeting.textContent=firstName?`¡Bienvenido, ${firstName}!`:'¡Bienvenido a CyberQuest!';
  const grid=$('#moduleGrid'),admin=state.user?.role==='admin',finalUnlocked=state.score>=720;
  orderedModules.forEach((m,i)=>{const done=state.completed.has(m.id),open=isUnlocked(i),card=document.createElement('article'),stage=!open?'locked':done?'stone':'ready';card.className='module-card '+stage;card.innerHTML=`<div class="module-glow" aria-hidden="true"></div><div class="card-icon">${done?'🔓':open?m.icon:'🔒'}</div><p class="module-state">${done?'Misión superada':open?'Misión disponible':'Misión bloqueada'}</p><h3>${m.title}</h3><p>${open?m.subtitle:'Completá el módulo anterior para iluminar este desafío.'}</p><div class="card-footer">${done?'<span class="badge">✓ Aprobado</span>':open?`<span>Meta: ${pointsPill(passScores[m.id])}</span>`:'<span>🔒 Bloqueado</span>'}<button class="start" ${open?'data-module="'+m.id+'"':'disabled'}>${done?'Repasar →':open?'Comenzar →':'🔒'}</button></div>`;grid.append(card)});
  const final=document.createElement('section');
  final.className=`final-banner final-gold ${finalUnlocked||admin?'':'final-locked'}`;
  final.innerHTML=`<div class="gold-bar" aria-hidden="true"><span>AU</span></div><div class="final-copy"><p class="eyebrow">EVALUACIÓN INTEGRAL</p><h2>Desafío final</h2><p>Combiná los seis temas para conquistar el desafío CyberQuest.</p><small>Necesitás al menos <b>720 pts</b> para desbloquearlo.</small></div><button class="primary" ${finalUnlocked||admin?'data-action="final"':'disabled'}>${finalUnlocked||admin?'Desbloquear →':'🔒 720 pts'}</button>`;
  grid.after(final);
  if(admin){const panel=document.createElement('section');panel.className='admin-panel';panel.innerHTML=`<p class="eyebrow">ADMINISTRACIÓN</p><h2>Autorizar admin</h2><form id="promoteForm"><input name="email" type="email" placeholder="Email de la cuenta" required><button class="primary">Autorizar</button></form><small id="promoteResult"></small>`;(document.querySelector('.challenge-banner')||final).after(panel);$('#promoteForm').onsubmit=promoteAdmin}
  $('#moduleCounter').textContent=`${state.completed.size} de ${modules.length} aprobados`;updateHeader();focusApp()
}
function renderLanding(){renderDashboard();$('.section-head').remove();$('#moduleGrid').remove();$('.challenge-banner').remove();$('.final-banner').remove();$('.reset-link').remove();document.querySelector('.admin-panel')?.remove();const benefits=document.createElement('section');benefits.className='landing-benefits';benefits.innerHTML=`<p class="eyebrow">UNA CULTURA DE SEGURIDAD</p><h2>Aprender haciendo cambia los hábitos.</h2><p>CyberQuest transforma conceptos de ciberseguridad en decisiones concretas para que las personas reconozcan riesgos, cuiden la información y actúen con confianza.</p><div class="benefit-grid"><article><span>🎯</span><h3>Situaciones reales</h3><p>Decisiones del día a día, personal o laboral.</p></article><article><span>🧩</span><h3>Aprendizaje activo</h3><p>Trivias, desafíos y juegos que refuerzan cada concepto.</p></article><article><span>🛡️</span><h3>Personas y equipos más seguros</h3><p>Una experiencia para prevenir engaños y errores cotidianos.</p></article></div></section>`;$('.hero').after(benefits);focusApp()}
function renderModule(id,step=0){const m=modules.find(x=>x.id===id);if(!isUnlocked(orderedModules.indexOf(m)))return;state.moduleSteps[id]=step;app.replaceChildren(clone('moduleTemplate'));$('#moduleHeader').innerHTML=`<div class="card-icon">${m.icon}</div><div><h1>${m.title}</h1><p>${m.subtitle}</p></div>`;const labels=['1. Aprendé','2. Decidí','3. Aprendé','4. Decidí','5. Trivia','6. Aprendé','7. Trivia'];labels.forEach((l,i)=>{const b=document.createElement('button');b.className='step '+(i===step?'active':'');b.textContent=l;b.disabled=state.user?.role!=='admin'&&i>step;b.onclick=()=>renderModule(id,i);$('#stepper').append(b)});const box=$('#activity');if(step===0)renderLearn(box,m,0);if(step===1)renderScenario(box,m,0);if(step===2)renderLearn(box,m,1);if(step===3)renderScenario(box,m,1);if(step===4)renderQuiz(box,m,0,0);if(step===5)renderLearn(box,m,2);if(step===6)renderQuiz(box,m,0,1);updateHeader();focusApp()}
function renderLearn(box,m,phase){const c=miniChallengeFor(m,phase),details=learnDetails[m.id]||[],pointGroups=[[0],[1,2],[3]],phaseDetails=phase===2?details.slice(2):[details[phase]],phasePoints=pointGroups[phase].map(i=>m.learn.points[i]).filter(Boolean),nextSteps=[1,3,6],nextLabels=['Ir a la situación →','Ver la próxima situación →','Ir a la trivia final →'];box.innerHTML=`<article class="activity-card"><p class="eyebrow">CONTENIDO EDUCATIVO · BLOQUE ${phase+1} DE 3</p><h2>${phase===0?m.learn.title:phase===1?'Profundizá el concepto':'Llevá el conocimiento a la práctica'}</h2>${phase===0?`<p>${m.learn.intro}</p>`:''}<div class="learn-details">${phaseDetails.map(text=>`<p>${text}</p>`).join('')}</div><div class="learning-points">${phasePoints.map(x=>`<div class="learning-point"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div><section class="mini-challenge"><p class="eyebrow">MINI DESAFÍO · PRACTICÁ LO APRENDIDO</p><h3>${c.prompt}</h3><div class="options">${shuffledOptions(c.options,c.prompt).map(({text,index})=>`<button class="option" data-mini="${index}">${text}</button>`).join('')}</div><div class="mini-feedback"></div></section><div class="activity-footer"><button class="primary" id="nextActivity" disabled>${nextLabels[phase]}</button></div></article>`;box.querySelectorAll('[data-mini]').forEach(b=>b.onclick=()=>answerMini(b,c,m,nextSteps[phase]))}
function answerMini(button,c,m,nextStep){const correct=+button.dataset.mini===c.answer;document.querySelectorAll('[data-mini]').forEach(b=>{b.disabled=true;if(+b.dataset.mini===c.answer)b.classList.add('correct')});if(!correct)button.classList.add('wrong');$('.mini-feedback').innerHTML=`<div class="feedback ${correct?'good':'bad'}"><b>${correct?'¡Muy bien! ':'Para recordar: '}</b>${c.feedback}</div>`;$('#nextActivity').disabled=false;$('#nextActivity').onclick=()=>renderModule(m.id,nextStep)}
function scenarioNarrative(text){const quote=text.match(/^(.*?):\s*[“"](.+?)[”"]$/);return quote?`<p class="scenario-context">${quote[1]}:</p><div class="chat-bubble">${quote[2]}</div>`:`<p class="scenario-context">${text}</p>`}
function renderScenario(box,m,index){const s=index?extraActivities[m.id].scenario:m.scenario,visual=s.image?`<img src="${s.image}" alt="${s.person||'Personaje de la situación'}">`:`<div class="scenario-visual" aria-hidden="true">${s.visual}</div>`;box.innerHTML=`<article class="activity-card"><p class="eyebrow">SITUACIÓN COTIDIANA ${pointsPill(20)}</p><h2>${s.title}</h2><div class="scenario with-person">${visual}<div class="scenario-content">${scenarioNarrative(s.text)}</div></div><div class="options">${shuffledOptions(s.options,s.title).map(({text,index})=>`<button class="option" data-answer="${index}">${text}</button>`).join('')}</div><div id="feedback"></div></article>`;box.querySelectorAll('.option').forEach(b=>b.onclick=()=>answerScenario(b,m,index))}
function answerScenario(button,m,index){const s=index?extraActivities[m.id].scenario:m.scenario,correct=+button.dataset.answer===s.answer,box=$('#activity'),next=index?4:2;box.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(+b.dataset.answer===s.answer)b.classList.add('correct')});if(!correct)button.classList.add('wrong');if(correct){state.score+=20;state.moduleScores[m.id]=(state.moduleScores[m.id]||0)+20;celebrate()}$('#feedback').innerHTML=`<div class="feedback ${correct?'good':'bad'}"><b>${correct?'¡Buena decisión! ':'Veamos por qué. '}</b>${s.feedback}${correct?' '+pointsPill(20):''}</div><div class="activity-footer"><button class="primary" id="goQuiz">${index?'Ir a la trivia →':'Continuar aprendiendo →'}</button></div>`;$('#goQuiz').onclick=()=>renderModule(m.id,next);updateHeader()}
function renderQuiz(box,m,index,round){const quiz=round?extraActivities[m.id].quiz:m.quiz,q=quiz[index];box.innerHTML=`<article class="activity-card"><p class="eyebrow">TRIVIA ${pointsPill(40)} · ${index+1} DE ${quiz.length}</p><h2>${q[0]}</h2><div class="options">${shuffledOptions(q[1],q[0]).map(({text,index},position)=>`<button class="option" data-answer="${index}">${String.fromCharCode(65+position)}. ${text}</button>`).join('')}</div><div id="feedback"></div></article>`;box.querySelectorAll('.option').forEach(b=>b.onclick=()=>answerQuiz(b,m,index,round))}
function answerQuiz(button,m,index,round){const quiz=round?extraActivities[m.id].quiz:m.quiz,q=quiz[index],correct=+button.dataset.answer===q[2];document.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(+b.dataset.answer===q[2])b.classList.add('correct')});if(!correct)button.classList.add('wrong');if(correct){state.score+=40;state.moduleScores[m.id]=(state.moduleScores[m.id]||0)+40;celebrate()}$('#feedback').innerHTML=`<div class="feedback ${correct?'good':'bad'}"><b>${correct?'¡Correcto! ':'Respuesta correcta. '}</b>${q[3]}${correct?' '+pointsPill(40):''}</div><div class="activity-footer"><button class="primary" id="nextQuestion">${index<quiz.length-1?'Siguiente pregunta →':round?'Ver resultado del módulo ✓':'Seguir aprendiendo →'}</button></div>`;$('#nextQuestion').onclick=()=>index<quiz.length-1?renderQuiz($('#activity'),m,index+1,round):round?completeModule(m):renderModule(m.id,5);updateHeader()}
function completeModule(m){const points=state.moduleScores[m.id]||0,minimum=passScores[m.id],passed=points>=minimum;if(passed){state.completed.add(m.id);playUnlockSound();showUnlockCinematic(m.title)}$('#activity').innerHTML=`<article class="activity-card completion"><div class="big">${passed?'🏆':'📘'}</div><p class="eyebrow">${passed?'MÓDULO APROBADO':'AÚN NO APROBADO'}</p><h2>${pointsPill(points)} de este módulo</h2><p>${passed?`Superaste la meta de ${pointsPill(minimum)} en <b>${m.title}</b>. El próximo módulo ya está desbloqueado.`:`Necesitás ${pointsPill(minimum)} para aprobar. Repasá el contenido y volvé a intentarlo.`}</p><button class="primary" ${passed?'data-action="modules"':'id="retryModule"'}>${passed?'Ver mis módulos':'Reintentar módulo'}</button></article>`;if(!passed)$('#retryModule').onclick=()=>{state.moduleScores[m.id]=0;renderModule(m.id,0)};updateHeader()}
function renderFinalChallenge(index=0,answers=[]){app.replaceChildren(clone('moduleTemplate'));$('#moduleHeader').innerHTML=`<div class="card-icon">🏆</div><div><h1>Desafío final</h1><p>Una evaluación integral de los seis módulos.</p></div>`;$('#stepper').remove();const item=finalQuestions[index],m=modules.find(x=>x.id===item.module);$('#activity').innerHTML=`<article class="activity-card"><p class="eyebrow">DESAFÍO FINAL · ${index+1} DE ${finalQuestions.length}</p><p class="question-count">Tema: ${m.icon} ${m.title}</p><h2>${item.q}</h2><div class="options">${shuffledOptions(item.o,item.q).map(({text,index},position)=>`<button class="option" data-final="${index}">${String.fromCharCode(65+position)}. ${text}</button>`).join('')}</div><div id="feedback"></div></article>`;document.querySelectorAll('[data-final]').forEach(b=>b.onclick=()=>answerFinal(b,item,index,answers))}
function answerFinal(button,item,index,answers){const correct=+button.dataset.final===item.a;document.querySelectorAll('[data-final]').forEach(b=>{b.disabled=true;if(+b.dataset.final===item.a)b.classList.add('correct')});if(!correct)button.classList.add('wrong');const next=[...answers,correct];$('#feedback').innerHTML=`<div class="feedback ${correct?'good':'bad'}"><b>${correct?'¡Correcto! ':'Respuesta a reforzar. '}</b>${correct?'Reconociste la práctica segura.':'Revisá este concepto antes de continuar.'}</div><div class="activity-footer"><button class="primary" id="nextFinal">${index<finalQuestions.length-1?'Siguiente desafío →':'Ver mi resultado final →'}</button></div>`;$('#nextFinal').onclick=()=>index<finalQuestions.length-1?renderFinalChallenge(index+1,next):renderFinalResult(next)}
function renderFinalResult(answers){const score=Math.round(answers.filter(Boolean).length/finalQuestions.length*100),weak=finalQuestions.find((_,i)=>!answers[i]),weakModule=weak&&modules.find(m=>m.id===weak.module);$('#activity').innerHTML=`<article class="activity-card completion"><div class="big">${score>=80?'🏆':'📘'}</div><p class="eyebrow">RESULTADO INTEGRAL</p><h2>${score}% de respuestas correctas</h2><p>${score>=80?'Excelente desempeño: aplicaste prácticas seguras en la mayoría de las situaciones.':`Área recomendada para reforzar: <b>${weakModule.icon} ${weakModule.title}</b>. Repasá ese módulo para afianzar el concepto.`}</p><div class="result-grid">${modules.map(m=>{const i=finalQuestions.findIndex(q=>q.module===m.id);return `<span>${answers[i]?'✓':'⚠'} ${m.title}</span>`}).join('')}</div><button class="primary" data-action="modules">Ver mis módulos</button></article>`;focusApp()}
function newHangman(){const item=hangmanWords[Math.floor(Math.random()*hangmanWords.length)];state.hangman={...item,guessed:[],errors:0,finished:false};renderHangman();$('#definition').insertAdjacentHTML('afterbegin','<span class="threat-icon">🦠</span>')}
function renderHangman(){if(!state.hangman)newHangman();app.replaceChildren(clone('hangmanTemplate'));const h=state.hangman;$('#definition').innerHTML=`<b>Definición:</b> ${h.definition}`;$('#word').textContent=[...h.word].map(l=>h.guessed.includes(l)?l:'_').join(' ');$('#mistakes').textContent=h.errors;const set='ABCDEFGHIJKLMNÑOPQRSTUVWXYZ';for(const l of set){const b=document.createElement('button');b.className='letter';b.textContent=l;b.disabled=h.guessed.includes(l)||h.finished;b.onclick=()=>guess(l);$('#letters').append(b)};$('.gallows').classList.add('error-'+h.errors);if(h.finished){const won=h.word.split('').every(l=>h.guessed.includes(l));$('.gallows-card').classList.add(won?'won':'lost');$('#gameMessage').innerHTML=won?'¡Concepto descubierto! '+pointsPill(20):'La palabra era '+h.word+'. ¡Probá otra!'}updateHeader();focusApp()}
function guess(letter){const h=state.hangman;if(h.finished)return;h.guessed.push(letter);if(!h.word.includes(letter))h.errors++;if(h.word.split('').every(l=>h.guessed.includes(l))){h.finished=true;state.score+=20}else if(h.errors>=5)h.finished=true;renderHangman()}
function renderSignals(index=0,score=0){const item=signalChallenges[index];app.replaceChildren(clone('moduleTemplate'));$('#moduleHeader').innerHTML=`<div class="card-icon">🔎</div><div><h1>Detectá las señales</h1><p>Un minijuego para practicar decisiones simples ante situaciones cotidianas.</p></div>`;$('#stepper').remove();$('#activity').innerHTML=`<article class="activity-card"><p class="eyebrow">MINIJUEGO · ${index+1} DE ${signalChallenges.length}</p><h2>${item.title}</h2><div class="scenario"><div class="scenario-visual" aria-hidden="true">💬</div><div class="scenario-content"><p class="scenario-context">${item.text}</p></div></div><p class="eyebrow">SEÑALES PARA DETECTAR</p><div class="signal-list">${item.signals.map((signal,signalIndex)=>`<div class="signal-row"><span>SEÑAL N.º ${signalIndex+1}</span><strong>${signal}</strong></div>`).join('')}</div><h3>¿Cuál es la respuesta más segura?</h3><div class="options"><button class="option" data-signal="safe">${item.answer}</button><button class="option" data-signal="risky">Abrirlo o conectarlo para comprobar si realmente hay un problema.</button><button class="option" data-signal="wait">Esperar, porque si fuera importante alguien volverá a escribir.</button></div><div id="feedback"></div></article>`;document.querySelectorAll('[data-signal]').forEach(button=>button.onclick=()=>answerSignal(button,index,score))}
function answerSignal(button,index,score){const correct=button.dataset.signal==='safe',item=signalChallenges[index];document.querySelectorAll('[data-signal]').forEach(b=>{b.disabled=true;if(b.dataset.signal==='safe')b.classList.add('correct')});if(!correct)button.classList.add('wrong');const nextScore=score+(correct?1:0);$('#feedback').innerHTML=`<div class="feedback ${correct?'good':'bad'}"><b>${correct?'¡Bien visto! ':'Para recordar: '}</b>${item.answer}</div><div class="activity-footer"><button class="primary" id="nextSignal">${index<signalChallenges.length-1?'Siguiente situación →':'Ver resultado →'}</button></div>`;$('#nextSignal').onclick=()=>index<signalChallenges.length-1?renderSignals(index+1,nextScore):renderSignalsResult(nextScore)}
function renderSignalsResult(score){$('#activity').innerHTML=`<article class="activity-card completion"><div class="big">🔎</div><p class="eyebrow">MIRADA ENTRENADA</p><h2>${score} de ${signalChallenges.length} señales resueltas</h2><p>${score===signalChallenges.length?'Reconociste cuándo conviene frenar y verificar. Esa pausa puede evitar muchos engaños.':'La clave es simple: frente a la urgencia o a algo inesperado, frená, verificá por un canal conocido y pedí ayuda.'}</p><button class="primary" data-action="modules">Volver a mis módulos</button></article>`;focusApp()}
function focusApp(){setTimeout(()=>app.focus(),0)}
function renderAuth(message='',mode='login'){$('#logoutBtn').classList.add('hidden');const register=mode==='register',savedEmail=localStorage.getItem('cq_saved_email')||'';app.innerHTML=`<section class="auth-card auth-single"><p class="eyebrow">CYBERQUEST · ACCESO SEGURO</p><h1>${register?'Creá tu cuenta':'Ingresá a tu recorrido'}</h1><p>${register?'Completá tus datos para comenzar.':'Entrená con situaciones reales y protegé la información.'}</p>${message?`<div class="auth-message">${message}</div>`:''}<div class="auth-grid"><form id="authForm"><h2>${register?'Registrate':'Iniciar sesión'}</h2>${register?'<input name="name" autocomplete="name" placeholder="Nombre y apellido" required>':''}<input name="email" type="email" autocomplete="username" value="${savedEmail}" placeholder="Email" required><input name="password" type="password" autocomplete="${register?'new-password':'current-password'}" ${register?'minlength="8" placeholder="Contraseña (mín. 8 caracteres)"':'placeholder="Contraseña"'} required>${register?'':`<label class="remember-option"><input name="remember" type="checkbox" checked> Mantener mi sesión iniciada</label><label class="remember-option"><input name="rememberEmail" type="checkbox" checked> Recordar mi email</label><p class="password-note">Tu navegador puede ofrecer guardar la contraseña de forma segura.</p>`}<button class="primary">${register?'Crear cuenta':'Ingresar'}</button><p class="auth-switch">${register?'¿Ya tenés una cuenta?':'¿No tenés cuenta?'} <button type="button" id="switchAuth">${register?'Iniciá sesión':'Registrate'}</button></p></form></div></section>`;$('#authForm').onsubmit=e=>submitAuth(e,register?'/api/register':'/api/login');$('#switchAuth').onclick=()=>renderAuth('',register?'login':'register')}
function localAuth(data,url){const users=JSON.parse(localStorage.getItem('cq_demo_users')||'[]'),email=String(data.email||'').trim().toLowerCase();const demo=users.find(u=>u.email==='admin@cyberquest.demo');if(demo){demo.name='Administrador';demo.role='admin';demo.password='admin123'}else users.push({id:'cq-demo-admin',name:'Administrador',email:'admin@cyberquest.demo',password:'admin123',role:'admin'});if(url.includes('register')){if(users.some(u=>u.email===email))throw new Error('Ese email ya está registrado. Iniciá sesión con esa cuenta.');const user={id:crypto.randomUUID(),name:String(data.name||'').trim(),email,password:data.password,role:'user'};users.push(user);localStorage.setItem('cq_demo_users',JSON.stringify(users));localStorage.setItem('cq_demo_session',JSON.stringify(user));return {user}}const user=users.find(u=>u.email===email&&u.password===data.password);if(!user)throw new Error('Email o contraseña incorrectos.');const storage=data.remember?localStorage:sessionStorage;localStorage.removeItem('cq_demo_session');sessionStorage.removeItem('cq_demo_session');storage.setItem('cq_demo_session',JSON.stringify(user));if(data.rememberEmail)localStorage.setItem('cq_saved_email',email);else localStorage.removeItem('cq_saved_email');localStorage.setItem('cq_demo_users',JSON.stringify(users));return {user}}
async function submitAuth(event,url){event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form));data.email=String(data.email||'').trim().toLowerCase();data.remember=Boolean(data.remember);data.rememberEmail=Boolean(data.rememberEmail);try{let result;if(state.localMode)result=localAuth(data,url);else{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});result=await response.json();if(!response.ok)throw new Error(result.error);if(data.rememberEmail)localStorage.setItem('cq_saved_email',data.email);else localStorage.removeItem('cq_saved_email')}if(result.user){state.user=result.user;renderDashboard()}else renderAuth(result.message)}catch(error){renderAuth(error.message)}}
async function promoteAdmin(event){event.preventDefault();const email=new FormData(event.currentTarget).get('email'),result=await fetch('/api/admin/promote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})}).then(r=>r.json());$('#promoteResult').textContent=result.message||result.error}
async function logout(){if(state.localMode){localStorage.removeItem('cq_demo_session');sessionStorage.removeItem('cq_demo_session')}else await fetch('/api/logout',{method:'POST'});state.user=null;state.score=0;state.completed.clear();renderAuth('Sesión cerrada correctamente.')}
async function initialize(){const savedUser=readSavedUser(),isStaticDemo=location.protocol==='file:'||location.hostname.endsWith('.github.io');if(isStaticDemo){state.localMode=true;state.user=savedUser;return state.user?renderDashboard():renderAuth('Modo demostración: las cuentas se guardan solo en este navegador.')}try{const response=await fetch('./api/session');if(!response.ok)throw new Error('Sesión no disponible');const session=await response.json();state.user=session.user;if(!state.user)return renderAuth();renderDashboard()}catch{state.localMode=true;state.user=savedUser;return state.user?renderDashboard():renderAuth('Modo demostración: las cuentas se guardan solo en este navegador.')}}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-action],[data-module]');if(!btn)return;if(btn.dataset.module)renderModule(btn.dataset.module);const a=btn.dataset.action;if(a==='dashboard')renderLanding();if(a==='continue'||a==='modules')renderDashboard();if(a==='hangman')newHangman();if(a==='signals')renderSignals();if(a==='newWord')newHangman();if(a==='final')renderFinalChallenge();if(a==='reset'){state.score=0;state.completed.clear();state.moduleSteps={};renderDashboard()}});
document.querySelector('#homeBtn').onclick=()=>state.user?renderLanding():renderAuth();initialize().catch(()=>{state.localMode=true;state.user=null;renderAuth('No se pudo restaurar una sesión anterior. Ingresá o registrate para continuar.')});
$('#logoutBtn').onclick=logout;
