import pabloImage from '../assets/characters/pablo.png';
import martinImage from '../assets/characters/martin.png';
import carlaImage from '../assets/characters/carla.png';
import sofiaImage from '../assets/characters/sofia.png';

export const courseModules = [
  {
    id: 'passwords', icon: '🔐', title: 'Contraseñas', subtitle: 'Protegé el acceso a tus cuentas',
    learn: { title: 'Una contraseña cuida la primera puerta', intro: 'Las contraseñas son personales y no se comparten. Una clave extensa y única reduce el riesgo de accesos no autorizados.', details: ['Una contraseña es una prueba de identidad. Si otra persona la conoce, puede actuar con tu cuenta, consultar información o enviar mensajes en tu nombre.', 'Una frase de contraseña con palabras no relacionadas es más difícil de adivinar que un nombre, una fecha o una secuencia.', 'MFA significa autenticación multifactor: además de la contraseña, la cuenta pide una segunda prueba de identidad, como un código temporal enviado a tu celular o generado por una app. Ese código confirma que sos vos; por eso nunca debe compartirse ni aprobarse si no lo solicitaste.'], points: [['Creá frases largas', 'Usá al menos 8 caracteres y combiná palabras, números o símbolos. Cuanto más larga y única sea, mejor.'], ['Evitá lo predecible', 'No uses fechas de nacimiento, nombres ni secuencias como 123456.'], ['Mantenela privada', 'No la envíes por correo, chat ni se la prestes a colegas.'], ['Sumá una capa', 'MFA agrega una segunda barrera: el código temporal también es secreto.']] },
    minis: [q('María usaba Maria123. ¿Cuál es una contraseña más segura?', ['Maria2026!', 'M4ria123!', 'Río!Luna_84#Tren'], 2, 'Una frase larga, única y sin datos personales es mucho más difícil de adivinar.'), q('Si una cuenta o usuario personal sufre una filtración, ¿qué evita que afecte a tus otras cuentas?', ['Usar una contraseña única por cuenta', 'Usar el mismo patrón en todas', 'Cambiar solo un número'], 0, 'Las claves únicas limitan el impacto de una filtración.'), q('¿Qué hacés ante una aprobación MFA que no solicitaste?', ['La aprobás por si acaso', 'No la aprobás y verificás o reportás', 'Compartís el código con soporte'], 1, 'Una solicitud inesperada puede indicar que alguien intenta ingresar a tu cuenta.')],
    scenarios: [s('Un acceso “urgente”', 'Pablo · compañero de oficina', pabloImage, 'Pablo, tu compañero de oficina, te escribe por chat: “Estoy bloqueado y necesito cerrar una operación. ¿Me pasás tu contraseña por cinco minutos?”', ['Se la envío: es un compañero y la necesita con urgencia.', 'Le indico que use el proceso oficial de recuperación o contacte a soporte.', 'Le presto mi equipo con la sesión abierta.'], 1, 'Las credenciales son personales e intransferibles. La urgencia nunca justifica compartirlas.'), { ...s('La nota junto a la compu', 'Pablo · compañero', pabloImage, 'Pablo dejó una nota con su contraseña junto al monitor porque así puede recordarla con facilidad.', ['Le sugiero retirarla y usar una frase de contraseña o un gestor seguro.', 'Le propongo guardar la nota dentro de un cajón con llave.', 'Le sugiero cambiar la clave cada semana y conservarla anotada.'], 0, 'Las contraseñas no deben quedar a la vista. Una frase segura o un gestor evita exponerlas.'), note: 'Password: PabloCrazy123' }],
    quizzes: [q('¿Cuál es la práctica más segura?', ['Reutilizar una contraseña conocida.', 'Usar una frase de contraseña larga y única.', 'Cambiar una letra por un número en mi fecha de nacimiento.'], 1, 'Una frase larga, única y difícil de predecir protege mejor la cuenta.'), q('¿Qué acción compromete una contraseña robusta?', ['Guardarla en un gestor seguro aprobado.', 'Compartirla por correo no cifrado.', 'Activar la verificación en dos pasos.'], 1, 'Una clave fuerte deja de ser segura cuando se comparte por medios inseguros.'), q('¿Para qué sirve la verificación en dos pasos?', ['Para sumar una capa de protección además de la contraseña.', 'Para que la aplicación sea más rápida.', 'Para evitar actualizar la clave.'], 0, 'El segundo factor dificulta el acceso aunque una contraseña sea comprometida.'), q('¿Qué dato conviene evitar en una contraseña?', ['Una fecha de nacimiento combinada con algo fácil de relacionar con vos.', 'Palabras aleatorias y no relacionadas.', 'Símbolos combinados con una frase extensa.'], 0, 'La información personal suele ser fácil de descubrir.'), q('¿Qué práctica reduce mejor el impacto de una filtración de datos?', ['Usar una clave única por cuenta.', 'Reutilizar una clave robusta en sitios de confianza.', 'Cambiar la misma clave en todos los servicios.'], 0, 'Las claves únicas reducen el impacto de una filtración.')] },
  {
    id: 'email', icon: '✉️', title: 'Correo personal / corporativo', subtitle: 'Usá cada una de tus cuentas con cuidado',
    learn: { title: 'Un correo puede abrir una puerta o una trampa', intro: 'El correo sirve, entre otras cosas, para conversar, comprar, estudiar y trabajar. Por eso conviene separar las cuentas personales de las profesionales y mirar cada mensaje con atención antes de actuar.', details: ['Una cuenta de correo personal es para tu vida privada; una cuenta de trabajo puede tener reglas y protecciones propias.', 'Muchos engaños copian logos, usan nombres conocidos, generan urgencia o piden claves y pagos. Revisá quién escribe, el dominio y el enlace.', 'No abras adjuntos inesperados. Si dudás, preguntá por otro canal conocido o pedí ayuda.'], points: [['Separá lo personal de lo laboral', 'No reenvíes documentos o información sensible del trabajo a tu correo personal.'], ['Verificá antes de actuar', 'Revisá remitente, dominio, enlaces y adjuntos antes de abrirlos.'], ['Informá lo sospechoso', 'Los mensajes falsos suelen generar urgencia o pedir claves.'], ['Usá recursos autorizados', 'Compartí archivos solo mediante plataformas y destinatarios aprobados.']] },
    minis: [q('¿Qué revisás antes de abrir un enlace?', ['El remitente, dominio y destino del enlace.', 'El remitente y el asunto.', 'Solo el remitente.'], 0, 'Revisar el origen y el destino real ayuda a detectar mensajes fraudulentos.'), q('¿Qué verificás en un correo inesperado?', ['Remitente, dominio y enlace real', 'Solo el logo', 'La hora de recepción'], 0, 'Los detalles del origen ayudan a detectar una suplantación.'), q('¿Qué hacés con un adjunto ejecutable inesperado?', ['Lo abrís para revisarlo', 'No lo abrís y lo reportás', 'Lo reenviás a un compañero'], 1, 'Los archivos inesperados pueden contener malware.')],
    scenarios: [s('“¿Me lo reenviás a mi cuenta personal?”', 'Martín · compañero de equipo', martinImage, 'Martín te escribe: “No puedo entrar al correo del trabajo. Reenviame el archivo del proyecto a mi cuenta personal, así avanzo desde casa.”', ['Se lo reenvío porque conozco a Martín.', 'Le propongo esperar el acceso o usar el proceso y canal acordados.', 'Le mando capturas por una red social.'], 1, 'Los archivos de trabajo deben circular por los canales definidos.'), s('Un adjunto inesperado', 'Martín · compañero de equipo', martinImage, 'Martín te reenvía un correo inesperado con un archivo adjunto y te pide abrirlo “urgente” para validar datos.', ['Verifico el mensaje por un canal conocido y pido ayuda si parece sospechoso.', 'Abro el archivo en una ventana privada.', 'Le respondo el mismo correo para que confirme.'], 0, 'La urgencia es una señal común de phishing. Verificá por otro canal antes de abrir enlaces o adjuntos.')],
    quizzes: [q('¿Cuándo usar el correo personal?', ['Para reenviar un archivo laboral urgente.', 'Para guardar una copia de un informe.', 'Para asuntos personales, no para información o gestiones de la empresa.'], 2, 'El correo personal no tiene los mismos controles que una cuenta de trabajo.'), q('¿Qué puede indicar phishing?', ['Un mensaje que genera urgencia y pide credenciales.', 'Un boletín interno esperado.', 'Un correo verificado por otro canal.'], 0, 'La urgencia y el pedido de datos requieren verificación.'), q('¿Qué hacer con un enlace sospechoso?', ['Abrirlo en una ventana privada.', 'No interactuar y pedir ayuda o reportarlo.', 'Reenviarlo a todo el equipo.'], 1, 'No interactúes con enlaces sospechosos.'), q('¿Qué conviene revisar en un correo inesperado?', ['El remitente completo, el dominio y el destino real del enlace.', 'Solo si el saludo incluye tu nombre.', 'Que el logo se vea nítido.'], 0, 'Verificar remitente y enlaces ayuda a detectar fraudes.'), q('¿Dónde se comparten archivos con datos sensibles?', ['En plataformas autorizadas y con permisos correspondientes.', 'En correo personal si tiene contraseña.', 'Por una red social privada.'], 0, 'Las plataformas autorizadas mantienen los controles necesarios.')] },
  {
    id: 'data', icon: '🛡️', title: 'Protección de datos', subtitle: 'Cuidá tu información y la de otras personas',
    learn: { title: 'Los datos requieren decisiones seguras', intro: 'La información personal, financiera y de tarjetas puede usarse para fraudes o robos. Cuidarla es importante tanto en la vida diaria como en el trabajo.', details: ['La información también aparece en planillas, correos, fotos, conversaciones, documentos, celulares y archivos compartidos.', 'Antes de compartir un dato preguntate: ¿es necesario?, ¿la persona correcta lo necesita? y ¿estoy usando el medio adecuado?', 'Bloquear la pantalla, actualizar dispositivos y no usar nubes personales ayuda a proteger a otras personas.'], points: [['Reconocé información sensible', 'Documentos, tarjetas, credenciales, fotos privadas y datos de contacto no se comparten sin necesidad.'], ['Elegí canales seguros', 'No envíes información sensible por correos o chats personales.'], ['Conectate con cuidado', 'Evitá operaciones sensibles desde Wi-Fi público.'], ['Actualizá tus herramientas', 'Las actualizaciones corrigen problemas y protegen dispositivos.']] },
    minis: [q('¿Cuál de estos elementos requiere mayor protección?', ['Una noticia pública', 'El número de una tarjeta', 'El pronóstico del clima'], 1, 'Los datos financieros y personales son sensibles.'), q('¿Qué criterio guía el envío de información sensible?', ['Urgencia del pedido', 'Canal autorizado y destinatario validado', 'Que el archivo sea pequeño'], 1, 'La urgencia nunca reemplaza la validación y el canal seguro.'), q('En una Wi-Fi pública, ¿qué decisión reduce el riesgo?', ['Ingresar igual por ser rápido', 'Evitar operaciones sensibles y esperar una red confiable', 'Enviar datos en varios mensajes'], 1, 'Una red no verificada puede exponer información.')],
    scenarios: [s('La planilla desde el café', 'Carla · compañera de equipo', carlaImage, 'Carla te escribe: “Estoy en un café con Wi-Fi gratis. ¿Me mandás por acá la planilla con datos de contacto para adelantar trabajo?”', ['La envío por chat para no retrasar.', 'Le propongo esperar una conexión confiable y usar el canal acordado.', 'Le saco el título al archivo y la mando.'], 1, 'Los datos sensibles no deberían viajar por redes o canales no verificados.'), s('Una foto para terminar después', '', '📄', 'Terminás una tarea y pensás sacarle una foto a una lista con nombres y teléfonos para seguirla desde tu celular personal.', ['Uso solo las herramientas y canales acordados para guardar o compartir la lista.', 'La guardo en mi galería.', 'La envío a mi correo personal.'], 0, 'Los datos de otras personas deben guardarse mediante las herramientas acordadas.')],
    quizzes: [q('¿Por qué proteger los datos compartidos en internet?', ['Pueden usarse para fraudes o robos.', 'Hace que las páginas carguen más rápido.', 'Evita gastar batería.'], 0, 'Los datos personales pueden ser explotados.'), q('¿Qué se recomienda al usar Wi-Fi pública?', ['Ingresar a cuentas sensibles.', 'Evitar compras, pagos y operaciones sensibles.', 'Enviar información sensible si es urgente.'], 1, 'Las redes públicas pueden exponer la información transmitida.'), q('¿Qué medida suma protección a una cuenta?', ['Activar la verificación en dos pasos.', 'Compartir la clave con conocidos.', 'Desactivar actualizaciones.'], 0, 'Agrega una capa adicional de seguridad.'), q('¿Cuál requiere mayor protección?', ['Un correo de cumpleaños.', 'Una planilla con nombres, DNI y números de tarjeta.', 'Una invitación a reunión general.'], 1, 'Los datos identificables y financieros son sensibles.'), q('¿Qué ayuda a proteger un dispositivo?', ['Mantenerlo actualizado.', 'Posponer actualizaciones.', 'Actualizar solo juegos.'], 0, 'Las actualizaciones corrigen problemas de seguridad conocidos.')] },
  {
    id: 'threats', icon: '⚠️', title: 'Amenazas cibernéticas', subtitle: 'Reconocé ataques antes de que causen daño',
    learn: { title: 'Reconocer una amenaza permite frenarla', intro: 'No todos los ataques se ven igual. Conocer sus señales ayuda a actuar antes de que un mensaje, archivo o enlace afecte a una persona o una organización.', details: ['Una amenaza puede llegar por un correo, mensaje, llamada, archivo, código QR o una red Wi-Fi falsa. Urgencia y enlaces extraños son señales.', 'Malware puede dañar o espiar; ransomware puede bloquear archivos y pedir dinero. Phishing, smishing y vishing son engaños por correo, mensajes o llamadas.', 'No tenés que resolver un incidente solo: dejá de interactuar y reportalo por el canal disponible.'], points: [['Malware', 'Software diseñado para dañar o acceder a un equipo sin autorización.'], ['Ransomware', 'Malware que cifra o bloquea archivos y puede exigir un pago.'], ['Phishing, smishing y vishing', 'Engaños por correo, mensaje o llamada que buscan apurarte.'], ['Detené y reportá', 'No abras adjuntos dudosos. Verificá por un canal oficial.']] },
    minis: [q('Un correo urgente con enlace para “evitar un bloqueo” puede ser…', ['Phishing', 'Backup', 'Firewall'], 0, 'El phishing genera urgencia para robar información.'), q('¿Qué práctica ayuda a limitar el impacto de ransomware?', ['Copias de seguridad y actualizaciones', 'Desactivar el antivirus', 'Usar contraseñas de fábrica'], 0, 'Los respaldos y los parches son capas clave.'), q('Una alerta de acceso inusual, ¿qué requiere?', ['Validarla y escalarla si se confirma', 'Cerrar la alerta sin revisar', 'Cambiar todas las claves sin investigar'], 0, 'Una alerta debe analizarse siguiendo el procedimiento.')],
    scenarios: [s('El correo que bloquea la cuenta', '', '✉️', 'Joaquín recibe un correo que dice: “Tu cuenta será bloqueada hoy. Verificá tus datos ahora” e incluye un enlace.', ['Abro el enlace rápido.', 'Reconozco un posible phishing, no interactúo y lo reporto.', 'Lo reenvío a mis compañeros.'], 1, 'Un correo urgente que pide datos es una señal típica de phishing.'), s('El archivo “recibo”', '', '🦠', 'Te llega un archivo ejecutable llamado Recibo_urgente.exe desde un remitente que no reconocés.', ['No lo abro, verifico el origen y lo reporto.', 'Lo guardo para revisarlo luego.', 'Le cambio la extensión y lo abro.'], 0, 'Un archivo ejecutable inesperado puede contener malware.')],
    quizzes: [q('¿Qué describe mejor al ransomware?', ['Un programa que cifra o bloquea información.', 'Una actualización del sistema.', 'Un método para mejorar el Wi-Fi.'], 0, 'Busca impedir el acceso a datos y puede exigir un rescate.'), q('¿Qué tipo de engaño llega por llamada?', ['Vishing.', 'Smishing.', 'Spyware.'], 0, 'El vishing usa llamadas para suplantar identidades.'), q('¿Qué hacer ante un adjunto inesperado?', ['Abrirlo en modo privado.', 'Verificar y reportar antes de abrirlo.', 'Reenviarlo.'], 1, 'Detenerse, verificar y reportar limita el impacto.'), q('¿Por qué no pagar un rescate?', ['No garantiza recuperar información y financia ataques.', 'Porque demora demasiado.', 'Porque borra copias de seguridad.'], 0, 'La prevención, respaldos y reporte son la respuesta adecuada.'), q('¿Qué medio usa el smishing?', ['Mensajes de texto o mensajería.', 'Llamadas telefónicas.', 'Memorias USB.'], 0, 'Es phishing que llega por mensajería.')] },
  {
    id: 'social', icon: '🧑‍💻', title: 'Ingeniería social', subtitle: 'Protegé tu puesto y verificá identidades',
    learn: { title: 'El atacante puede buscar manipular a una persona', intro: 'La ingeniería social usa urgencia, confianza o autoridad aparente para lograr que alguien entregue datos, abra un acceso o realice una acción insegura.', details: ['Un atacante puede presentarse como técnico, proveedor, cliente o directivo; la presión busca que actúes antes de verificar.', 'Nunca compartas contraseñas, códigos de autenticación, accesos remotos ni documentación por llamadas o chats no verificados.', 'Bloquear pantalla, guardar documentos y reportar objetos desconocidos también forman parte de la seguridad cotidiana.'], points: [['Verificá la identidad', 'Que alguien conozca tu nombre no prueba quién es.'], ['No compartas secretos', 'Contraseñas y códigos MFA nunca se solicitan por llamada informal.'], ['Cuidá el puesto de trabajo', 'Bloqueá la pantalla al alejarte y resguardá documentos.'], ['Desconfiá de objetos desconocidos', 'Un USB encontrado debe reportarse, no conectarse.']] },
    minis: [q('¿Qué hacés ante una llamada “urgente” que pide tu código MFA?', ['Lo comparto', 'Corto y verifico por un canal oficial', 'Doy solo el código'], 1, 'La verificación oficial evita caer en una suplantación.'), q('¿Cómo validás a quien pide información por teléfono?', ['Por su tono de urgencia', 'Usando un canal oficial independiente', 'Porque conoce tu nombre'], 1, 'La identidad debe verificarse fuera de la comunicación sospechosa.'), q('¿Qué protege el puesto al alejarte?', ['Bloquear pantalla y resguardar documentos', 'Dejar la sesión abierta', 'Compartir el equipo'], 0, 'El control físico es una capa de seguridad diaria.')],
    scenarios: [s('“Soy de Sistemas, necesito tu código”', '', '☎️', 'Una persona llama a Sofía, dice ser de Sistemas y le pide usuario, contraseña y un código MFA para una actualización urgente.', ['Le doy el código.', 'No comparto datos y verifico el pedido con Sistemas por un canal oficial.', 'Le doy solo el código MFA.'], 1, 'La urgencia y la supuesta autoridad son recursos de manipulación.'), s('El USB encontrado', '', '💾', 'Nicolás encuentra un USB sin identificar en la recepción y piensa conectarlo para saber de quién es.', ['Lo reporta y no lo conecta.', 'Lo conecta en un equipo sin archivos importantes.', 'Lo lleva a casa.'], 0, 'Los USB desconocidos pueden contener malware y deben reportarse.')],
    quizzes: [q('¿Qué es tailgating?', ['Ingresar a un sector siguiendo a una persona autorizada.', 'Actualizar un antivirus.', 'Cambiar una contraseña.'], 0, 'No permitas accesos sin validar.'), q('¿Qué corresponde al alejarse del puesto?', ['Bloquear la pantalla.', 'Dejar sesión abierta.', 'Compartir el equipo.'], 0, 'Protege información y accesos.'), q('¿Qué hacer con un USB desconocido?', ['Conectarlo.', 'Reportarlo y no conectarlo.', 'Llevarlo a casa.'], 1, 'Puede contener software malicioso.'), q('¿Qué dato jamás se comparte en una llamada no verificada?', ['Contraseña o código MFA.', 'Horario general.', 'Nombre del sector.'], 0, 'Las credenciales son secretos.'), q('¿Qué ayuda a evitar shoulder surfing?', ['Proteger la pantalla y bloquearla.', 'Reducir brillo.', 'Dejar sesión abierta.'], 0, 'Resguardar pantalla evita que terceros observen información.')] },
  {
    id: 'grooming', icon: '👤', title: 'Grooming', subtitle: 'Detectá y reportá contactos riesgosos',
    learn: { title: 'Las señales importan', intro: 'El grooming es una forma de manipulación en línea en la que un adulto busca ganarse la confianza de menores para obtener información, imágenes o encuentros.', details: ['Puede comenzar con perfiles falsos, halagos, regalos, secretos o conversaciones aparentemente inocentes.', 'Señales como pedidos de secreto, presión para responder, preguntas sobre ubicación y cambios a chats privados requieren atención.', 'No confrontes ni borres evidencia: conservá capturas, bloqueá el contacto y buscá ayuda de un adulto responsable.'], points: [['Desconfiá de secretos y presiones', 'Pedidos de mantener conversaciones ocultas o fotos son señales de alerta.'], ['Cuidá la información', 'No compartas ubicación, rutinas, escuela ni imágenes con desconocidos.'], ['No borres evidencia', 'Conservá capturas para poder reportar.'], ['Acompañá y reportá', 'Escuchá sin culpar y buscá ayuda.']] },
    minis: [q('¿Qué señal requiere atención inmediata?', ['Un pedido de mantener secretos y enviar fotos', 'Una actualización de aplicación', 'Un saludo de un familiar'], 0, 'Los secretos, la presión y pedidos de imágenes son alertas.'), q('¿Qué conducta es una señal de manipulación?', ['Pedir secretos y aislar a la persona', 'Recomendar hablar con un adulto', 'Respetar límites'], 0, 'Los secretos buscan impedir que la víctima pida ayuda.'), q('¿Qué conviene conservar ante un contacto riesgoso?', ['Capturas y mensajes relevantes', 'Solo un nombre de usuario', 'Nada, borrar todo'], 0, 'La evidencia puede ayudar a reportar el caso.')],
    scenarios: [s('Consulta de una clienta', 'Sofía · clienta', sofiaImage, 'Sofía comenta que su hijo recibe mensajes de alguien que dice tener su edad, pide fotos y solicita que no se lo cuente a nadie.', ['Le recomiendo seguir hablando.', 'Le sugiero guardar evidencia, bloquear el contacto y buscar ayuda.', 'Le indico borrar todo.'], 1, 'Los secretos, pedidos de imágenes y presión son alertas.'), s('Un pedido de ayuda', 'Sofía · madre preocupada', sofiaImage, 'Sofía duda si debe borrar los mensajes sospechosos que recibió su hijo antes de hablar con un adulto.', ['Le sugiero conservar capturas, bloquear y pedir ayuda.', 'Le sugiero borrar el chat.', 'Le propongo responder una vez.'], 0, 'Las capturas ayudan a pedir ayuda y reportar el caso.')],
    quizzes: [q('¿Cuál es una señal de alerta?', ['Un contacto pide mantener la conversación en secreto.', 'Un familiar envía un saludo.', 'Una aplicación se actualiza.'], 0, 'El secreto y aislamiento son tácticas frecuentes.'), q('¿Qué conviene hacer ante un posible caso?', ['Guardar evidencia y pedir ayuda.', 'Responder con amenazas.', 'Publicar conversación en redes.'], 0, 'Es importante acompañar y usar canales seguros.'), q('¿Qué dato no debe compartirse con desconocidos?', ['Ubicación y rutina.', 'Color favorito.', 'Recomendación de música.'], 0, 'Pueden poner en riesgo la seguridad personal.'), q('¿Qué combinación es una señal relevante?', ['Secretos, fotos y otro chat privado.', 'Publicación pública de un compañero.', 'Actualización disponible.'], 0, 'Aislamiento y secretos son señales de manipulación.'), q('¿Qué corresponde ante una señal de riesgo?', ['Bloquear, conservar evidencia y pedir ayuda.', 'Continuar conversación.', 'Publicar el chat.'], 0, 'Bloquear y buscar apoyo es una respuesta segura.')] }
];

export const finalQuestions = courseModules.flatMap(module => module.quizzes.slice(0, 2).map(item => ({ ...item, module: module.id }))).slice(0, 10);

function q(prompt, options, answer, feedback) { return { prompt, options, answer, feedback }; }
function s(title, person, visual, text, options, answer, feedback) { return { title, person, visual, text, options, answer, feedback }; }
